### ISSUE TITLE
아이폰 로그인 에러

### ISSUE THREAD

**Issue by sys09270883** [KhoraLee/ku-boost-iOS#23]
아이패드에서는 잘 되는데 아이폰에서 로그인 쪽 처리가 잘 안되는 경우가 있는 것 같습니다.

<kbd>
  <img src="https://user-images.githubusercontent.com/50787869/122573792-ee2dad80-d089-11eb-92cc-3f713852e317.png" width="32%" height="32%"/>
  <img src="https://user-images.githubusercontent.com/50787869/122573797-f0900780-d089-11eb-868a-d70f6dab18bf.png" width="32%" height="32%"/>
  <img src="https://user-images.githubusercontent.com/50787869/122573804-f259cb00-d089-11eb-8bd0-bf0bf90f38b5.png" width="32%" height="32%"/>
</kbd>

---

로그인 쪽 API에 헤더를 명시해야 하도록 수정되었습니다.

- 문제상황
<img src="https://user-images.githubusercontent.com/50787869/123301964-297f1f00-d557-11eb-8361-43bccfdd4d7b.png" width="50%" height="50%"/>

- 해결방법: `Host`, `Referer` 헤더 명시
![image](https://user-images.githubusercontent.com/50787869/123301811-03f21580-d557-11eb-89a0-68f9f492e803.png)

**Comment by KhoraLee** [comment]
- [ ] 로그인 및 성적 확인시에 referer 해더 추가
