### ISSUE TITLE
오즈 리포트 관련 처리

### ISSUE THREAD

**Issue by sys09270883** [KhoraLee/ku-boost-iOS#24]
API 헤더도 그렇고 오즈 리포트 관련해서도 수정이 있었습니다. 
서버 측에서 오즈 리포트 뷰어 스크립트에 암호화를 적용했고, 다시 분석해서 쓰는 것은 문제없지만 다양한 학과에 대해서 정규표현식 처리를 완벽하게 하는 것은 불가능할 것 같습니다.
따라서 취득학점확인원의 경우 예전처럼 웹뷰로 처리하는 방식으로 수정하려고 합니다.

**Comment by KhoraLee** [comment]
현재 iOS에는 OZ 관련 구현이 되어있지않으므로 이슈 닫도록 하겠습니다. 추후 웹뷰 기능 추가시 이슈 Reopen 하도록 하겠습니다.
